version: 2
sources:
  - name: rds
    database: fivetran_database
    freshness: 
      warn_after: {count: 12, period: hour}
    loaded_at_field: _fivetran_synced
    schema: postgres_northwinds_rds_public
    tables:
      - name: customers
        freshness:
          warn_after: {count: 6, period: hour}
      - name: suppliers
        freshness:
          warn_after: {count: 2, period: day}

          