version: 2

models: 
  - name: stg_hubspot_contacts
    columns:
      - name: first_name
        tests:
          - not_null
          - accepted_values:
              values: ['fran', 'daphne']
      - name: last_name
        tests:
          - not_null